USE bucket;

insert into goal(title, done, importance)
values ('See the Northern Light', false, 3),
	   ('Be a Googler', false, 4),
	   ('Learn an instrument', false, 4),
       ('Be physically fit', false, 5),
       ('Get a dog', false, 4),
       ('Start a business', false, 4),
       ('Go to Disneyworld', false, 3),
       ('Go to an NBA game', false, 4),
       ('Learn Japanese', false, 4),
       ('Star gazing', true, 4),
       ('Run a full marathon', false, 3),
       ('Go on a summer-long Road Trip around America with friends', false, 4),
       ('Work and travel', false, 3),
       ('Visit Grand Canyon', true, 3),
	   ('Have a signature dish', false, 5),
       ('Bike around Taiwan', false, 4),
       ('Listen to a Ted Talk live', false, 4),
       ('Develop an iOS application', false, 5),
       ('Complete a 21-day Chan Retreat', false, 5);
 
insert into category(cate_name)
values ('travel'),
	   ('lifestyle'),
       ('educational'),
       ('financial'),
       ('physical'),
       ('spiritual');
       
insert into goal_category(goal_id, cate_id)
values (1,1),
	   (2,2),
       (3,3),
       (4,5),
       (5,2),
       (6,4),
       (7,1),
       (8,1),
       (9,3),
       (10,2),
       (11,5),
       (12,1),
       (13,1),
       (13,4),
       (14,1),
       (15,2),
       (16,1),
       (16,5),
       (17,3),
       (18,3),
       (19,6);
       
insert into step(instruction, done, goal_id)
values ('Book an air ticket to Norway between October and March', false, 1),
	   ('Pack artic clothes and travel gear', false, 1),
       ('Enjoy the Northern lights', false, 1),
       ('Find out the job requirements of Google', false, 2),
       ('Acquire necessary skills', false, 2),
       ('Nail the interview', false, 2),
       ('Welcome to Google', false, 2),
       ('Choose an instrument', false, 3),
       ('Learn the basics of music', false, 3),
       ('Learn the basics of the instrument', false, 3),
       ('Practice, practice, and practice!', false, 3),
       ('Determine your targeted size', false, 4),
       ('Determine your Body Mass Index', false, 4),
       ('Have a meal plan tailored to fit your calories count', false, 4),
       ('Exercise multiple times weekly', false, 4),
       ('Maintain the plan for at least 3 months', false, 4),
       ('Find yourself looking great in the mirror', false, 4),
       ('Get a flight ticket to Orlando, Florida, USA', false, 5),
       ('Book a hotel', false, 5),
       ('Get the entry ticket for DisneyWorld', false, 5),
       ('Enjoy the Disney World', false, 5);
       