package com.sls.intern.millionaire.generatedentities;
// Generated Oct 4, 2018 3:02:26 PM by Hibernate Tools 5.1.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Correctans generated by hbm2java
 */
@Entity
@Table(name = "correctans", catalog = "dbQuestion2")
public class Correctans implements java.io.Serializable {

	private Integer caId;
	private String caContent;

	public Correctans() {
	}

	public Correctans(String caContent) {
		this.caContent = caContent;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "caID", unique = true, nullable = false)
	public Integer getCaId() {
		return this.caId;
	}

	public void setCaId(Integer caId) {
		this.caId = caId;
	}

	@Column(name = "caContent", length = 50)
	public String getCaContent() {
		return this.caContent;
	}

	public void setCaContent(String caContent) {
		this.caContent = caContent;
	}

}
