package com.sls.intern.millionaire.generatedentities;
// Generated Oct 4, 2018 3:02:26 PM by Hibernate Tools 5.1.8.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Question generated by hbm2java
 */
@Entity
@Table(name = "question", catalog = "dbQuestion2")
public class Question implements java.io.Serializable {
	
	private Integer qid;
	private String qcontent;
	private Correctans cAns;
	private Wrongans1 wa1;
	private Wrongans2 wa2;
	private Wrongans3 wa3;


	public Question() 
	{
		
	}
	
	public Question(String qcontent, Correctans cAns, Wrongans1 wa1, Wrongans2 wa2, Wrongans3 wa3) 
	{
		this.qcontent= qcontent;
		this.cAns= cAns;
		this.wa1 = wa1;
		this.wa2 = wa2;
		this.wa3 = wa3;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "qID", unique = true, nullable = false)
	public Integer getQid() {
		return this.qid;
	}

	public void setQid(Integer qid) {
		this.qid = qid;
	}

	@Column(name = "qContent", length = 50)
	public String getQcontent() {
		return this.qcontent;
	}

	public void setQcontent(String qcontent) {
		this.qcontent = qcontent;
	}

	@OneToOne(cascade = CascadeType.ALL)
	public Correctans getCAns() {
		return this.cAns;
	}

	public void setCAns(Correctans cAns) {
		this.cAns = cAns;
	}

	@OneToOne(cascade = CascadeType.ALL)
	public Wrongans1 getWa1() {
		return this.wa1;
	}

	public void setWa1(Wrongans1 wa1) {
		this.wa1 = wa1;
	}
	
	@OneToOne(cascade = CascadeType.ALL)
	public Wrongans2 getWa2() {
		return this.wa2;
	}

	public void setWa2(Wrongans2 wa2) {
		this.wa2 = wa2;
	}

	@OneToOne(cascade = CascadeType.ALL)
	public Wrongans3 getWa3() {
		return this.wa3;
	}

	public void setWa3(Wrongans3 wa3) {
		this.wa3 = wa3;
	}

}
