USE dbQuestion2;

INSERT INTO correctAns(caContent)
VALUES	('4'),
	('Asia'),
	('Osmium'),
	('Hercules'),
	('Thor'),
    ('Lebanon'),
    ('Good Morning'),
    ('8848 M'),
    ('6'),
    ('Moon of Jupiter'),
    ('Anemometer'),
    ('Wolf'),
    ('International Women''s Day'),
    ('Death of a Salesman'),
    ('Jeff Bezos'),
    ('Chinese'),
    ('Benjamin Franklin'),
    ('88'),
    ('Carolina Reaper'),
    ('Riki Tiki Tavi');
    
    
INSERT INTO wrongAns1(wa1Content)
VALUES
	('5'),
    ('Europe'),
    ('Gold'),
    ('Ares'),
    ('Scarlet Witch'),
    ('Cyprus'),
    ('Good Bye'),
    ('7986 M'),
    ('7'),
    ('Witch-king of Lord of the Rings'),
    ('Altimeter'),
    ('Snake'),
    ('Labor Day'),
    ('Julius Ceasar'),
    ('Bill Gates'),
    ('English'),
    ('Thomas Alva Edison'),
    ('91'),
    ('Ghost Pepper'),
    ('Old Fashioned');

 
INSERT INTO wrongAns2(wa2Content)
VALUES
	('3'),
    ('South America'),
    ('Plutonium'),
    ('Hephaestus'),
    ('Black Panther'),
    ('Ukraine'),
    ('I love you'),
    ('9121 M'),
    ('8'),
    ('Name of the new virus'),
    ('Osmometer'),
    ('Bear'),
    ('Earth Day'),
    ('The Tempest'),
    ('Mark Zuckerberg'),
    ('Spanish'),
    ('Niels Bohr'),
    ('82'),
    ('Pepper X'),
    ('Aviation');

INSERT INTO wrongAns3(wa3Content)
VALUES	
    ('22'),
	('Africa'),
	('Iridium'),
	('Demeter'),	
	('Doctor Strange'),
    ('Estonia'),
    ('Nice to meet you'),
    ('10334 M'),
    ('9'),
    ('A musical piece'),
    ('Seismeter'),
    ('Cow'),
    ('World Cancer Day'),
    ('As You Like It'),
    ('Larry Page'),
    ('Arabic'),
    ('Charles Darwin'),
    ('85'),
    ('Naga Viper'),
    ('Manhattan');    

INSERT INTO question(qcontent, caID, wa1ID, wa2ID, wa3ID)
VALUES('What 2 + 2?',1,1,1,1),
	('Where is Malaysia?', 2,2,2,2),
	('What is the densest metal?', 3,3,3,3),
	('Who is not a Greek God?', 4,4,4,4),
	('Who did Thanos not kill?', 5,5,5,5),
    ('Which country does not belong to Europe?',6,6,6,6),
    ('What does Ohayou mean in Japanese?',7,7,7,7),
    ('How tall is Mount Everest?',8,8,8,8),
    ('How many players are there in an ice hockey team?',9,9,9,9),
    ('What is Ganymede?',10,10,10,10),
    ('Which instrument is used to measure wind speed?',11,11,11,11),
    ('Canine refers to dog, Lupine refers to?',12,12,12,12),
    ('What day is March 8th?',13,13,13,13),
    ('Which play is not written by Shakespeare?',14,14,14,14),
    ('Who is the richest man on Earth?',15,15,15,15),
    ('Which is the most spoken language in the world?',16,16,16,16),
    ('Who discovered electricity?',17,17,17,17),
    ('How many keys are there in a piano?',18,18,18,18),
    ('What is the hottest pepper on Earth?',19,19,19,19),
    ('Which one of these is not a cocktail?',20,20,20,20);